# UDEMY COURSES DATASET

In [103]:
import pandas as pd

In [104]:
data = pd.read_csv(r'C:\Users\MATOVU MOSES\Desktop\Data Analysis\7. Udemy Courses.csv')

In [105]:
data.shape

(3682, 11)

In [106]:
data.head()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

### 1. What are all the Subjects for which Udemy is offering Courses?

In [107]:
data.subject.unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

### 2.  Which Subject has the Maximum number of Courses?

In [108]:
data.subject.value_counts()

Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: subject, dtype: int64

### 3. Show all Courses which are paid or free cost

In [109]:
data[data.is_paid == False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

In [110]:
data[data.is_paid == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

In [111]:
data.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments

### 5. Which are the Top Selling Courses

In [112]:
data.sort_values('num_subscribers', ascending = False).head(3)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development

### 5. Which are the Least Selling Courses

In [113]:
data.sort_values('num_subscribers', ascending = True)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development

### 7. Show all Courses of Graphice Design where price is below 100 ?

In [114]:
data[(data.subject == 'Graphic Design') & (data.price > '100')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
8,206592,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1 hour,2014-04-29T19:50:31Z,Graphic Design
20,1165268,15 Motion Graphic Elements in After Effect (S...,True,30,8,0,20,Intermediate Level,3 hours,2017-04-11T04:27:34Z,Graphic Design
35,1164876,3DS MAX - Learn 3Ds MAX tutorial for Beginners...,True,20,785,2,29,All Levels,4.5 hours,2017-04-18T16:45:59Z,Graphic Design
39,599652,48 Logo Designs and Techniques,True,20,113,9,48,All Levels,9 hours,2015-09-15T00:23:14Z,Graphic Design
52,794036,8 Stunden professionelles Cinema 4D Training,True,50,18,1,38,All Levels,8.5 hours,2016-03-22T20:51:28Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
3568,133968,Web Elements Design With Photoshop,True,45,5072,38,44,All Levels,5 hours,2014-10-21T19:18:12Z,Graphic Design
3588,1131780,"Whiteboard Animation, Beginner To Expert - In ...",True,20,1343,25,16,All Levels,1 hour,2017-03-14T20:52:30Z,Graphic Design
3639,1122306,Wordpress: Comment utiliser le thème FABLE,True,20,1,0,10,Beginner Level,39 mins,2017-03-07T16:53:27Z,Graphic Design
3671,144222,"YOU can Draw, Shade and Paint a Mixed Media Gi...",True,30,1249,44,19,Beginner Level,3 hours,2014-01-28T02:30:26Z,Graphic Design
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

### 8. List out all the courses that are related to Python

In [115]:
len(data[data.course_title.str.contains('Python')])

29

### 9. What the Courses that are published in 2015

In [116]:
data.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments

In [117]:
data.dtypes

course_id               int64
course_title           object
is_paid                  bool
price                  object
num_subscribers         int64
num_reviews             int64
num_lectures            int64
level                  object
content_duration       object
published_timestamp    object
subject                object
dtype: object

In [118]:
data['published_timestamp'] = pd.to_datetime(data.published_timestamp)

In [119]:
data.dtypes

course_id                            int64
course_title                        object
is_paid                               bool
price                               object
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration                    object
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [120]:
data['Year'] = data['published_timestamp'].dt.year

In [121]:
data[data.Year == 2011]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
431,11475,Become a Certified Web Developer,True,100,26673,1090,185,All Levels,12 hours,2011-12-20 15:29:25+00:00,Web Development,2011
447,11174,Become a Web Developer from Scratch,True,120,69186,2408,197,All Levels,27.5 hours,2011-11-19 21:51:20+00:00,Web Development,2011
1743,8325,HTML Tutorial: HTML & CSS for Beginners,True,20,12458,253,82,All Levels,4 hours,2011-09-09 15:28:59+00:00,Web Development,2011
1998,8324,Javascript for Beginners,True,20,3697,195,48,All Levels,3 hours,2011-07-09 05:43:31+00:00,Web Development,2011
2244,11153,Learn jQuery: An In-depth Course For Beginners,True,50,7014,95,62,All Levels,4.5 hours,2011-11-29 01:29:11+00:00,Web Development,2011

### 10. What are the Maximum number of subscription for each level of course

In [122]:
data.level.unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

In [123]:
data.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [124]:
data.groupby('level').max().head(50)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,content_duration,published_timestamp,subject,Year
level,,,,,,,,,,,
All Levels,1277924,６時間でインターバンク市場を攻略！最短距離でトレード基礎力,True,Free,268923,27445,544,9.5 hours,2017-07-06 21:16:13+00:00,Web Development,2017
Beginner Level,1282064,７日でマスター ビギナー向け Adobe Illustrator どきどきセミナー,True,Free,161029,5924,779,9.5 hours,2017-07-06 21:46:30+00:00,Web Development,2017
Expert Level,1275790,[Value Investing] Where White People Keep Thei...,True,95,5172,249,157,9 hours,2017-07-04 18:08:01+00:00,Web Development,2017
Intermediate Level,1276182,株式投資で本当のテクニカル分析ができるようになる,True,Free,29167,3326,320,9.5 hours,2017-07-05 04:41:54+00:00,Web Development,2017